version: '3'

services:
  db:
    container_name: "my_budget_db"
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"

  app:
    container_name: "my_nestjs_app"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DATABASE_PORT}/${POSTGRES_DB}"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
